2022-02-01 13:05:57,491 INFO    MainThread:58720 [wandb_setup.py:_flush():71] setting env: {}
2022-02-01 13:05:57,491 INFO    MainThread:58720 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-01 13:05:57,491 INFO    MainThread:58720 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\avpre\Documents\Trainings\mldevops\nd0821-c2-build-model-workflow-exercises\lesson-3-data-validation\demo\fixtures\wandb\run-20220201_130557-iqhtco13\logs\debug.log
2022-02-01 13:05:57,491 INFO    MainThread:58720 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\avpre\Documents\Trainings\mldevops\nd0821-c2-build-model-workflow-exercises\lesson-3-data-validation\demo\fixtures\wandb\run-20220201_130557-iqhtco13\logs\debug-internal.log
2022-02-01 13:05:57,491 INFO    MainThread:58720 [wandb_init.py:init():404] calling init triggers
2022-02-01 13:05:57,492 INFO    MainThread:58720 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-01 13:05:57,492 INFO    MainThread:58720 [wandb_init.py:init():460] starting backend
2022-02-01 13:05:57,492 INFO    MainThread:58720 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-02-01 13:05:57,505 INFO    MainThread:58720 [backend.py:ensure_launched():216] starting backend process...
2022-02-01 13:05:57,594 INFO    MainThread:58720 [backend.py:ensure_launched():221] started backend process with pid: 33600
2022-02-01 13:05:57,595 INFO    MainThread:58720 [wandb_init.py:init():469] backend started and connected
2022-02-01 13:05:57,596 INFO    MainThread:58720 [wandb_init.py:init():533] updated telemetry
2022-02-01 13:05:57,683 INFO    MainThread:58720 [wandb_init.py:init():563] communicating current version
2022-02-01 13:06:00,152 INFO    MainThread:58720 [wandb_init.py:init():568] got version response 
2022-02-01 13:06:00,152 INFO    MainThread:58720 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-01 13:06:00,608 INFO    MainThread:58720 [wandb_init.py:init():606] starting run threads in backend
2022-02-01 13:06:05,625 INFO    MainThread:58720 [wandb_run.py:_console_start():1810] atexit reg
2022-02-01 13:06:05,626 INFO    MainThread:58720 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-01 13:06:05,626 INFO    MainThread:58720 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-01 13:06:05,628 INFO    MainThread:58720 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-01 13:06:05,628 INFO    MainThread:58720 [wandb_init.py:init():633] run started, returning control to user process
2022-02-01 13:06:08,393 INFO    MainThread:58720 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-01 13:06:08,394 INFO    MainThread:58720 [wandb_run.py:_restore():1752] restore
2022-02-01 13:06:09,218 INFO    MainThread:58720 [wandb_run.py:_restore():1752] restore
2022-02-01 13:06:11,398 ERROR   MainThread:58720 [wandb_run.py:_atexit_cleanup():1798] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\avpre\anaconda3\envs\udacity\lib\site-packages\wandb\sdk\wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\avpre\anaconda3\envs\udacity\lib\site-packages\wandb\sdk\wandb_run.py", line 1958, in _on_finish
    print("")
ValueError: I/O operation on closed file.
